name: PostgreSQL Service Demo

on:
  push:
    paths:
      - '.github/workflows/postgres-service.yml'

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready on port 5432..."
          for i in {1..30}; do
            if nc -z localhost 5432; then
              echo "PostgreSQL is up!"
              exit 0
            fi
            echo "Waiting... ($i)"
            sleep 1
          done
          echo "PostgreSQL failed to start in time."
          exit 1

      - name: Confirm PostgreSQL service is accessible
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          PGPASSWORD=testpassword psql -h localhost -U testuser -d testdb -c '\l'
