name: PostgreSQL Service With Readiness Check

on:
  push:
    paths:
      - '.github/workflows/postgres-service.yml'

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client


      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          while ! nc -z localhost 5432; do   
            sleep 1
          done
          echo "PostgreSQL is ready!"

      - name: Confirm PostgreSQL connection with psql
        env:
          PGPASSWORD: testpassword
        run: |
          psql -h localhost -U testuser -d testdb -c '\l'
