name: PostgreSQL Service With Readiness Check

on:
  push:
    paths:
      - '.github/workflows/postgres-service.yml'

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready using pg_isready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U testuser
            if [ $? -eq 0 ]; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Still waiting... ($i)"
            sleep 1
            if [ $i -eq 30 ]; then
              echo "PostgreSQL didn't become ready in time."
              exit 1
            fi
          done

      - name: Confirm PostgreSQL connection with psql
        env:
          PGPASSWORD: testpassword
        run: |
          psql -h localhost -U testuser -d testdb -c '\l'
